// <auto-generated />
namespace SwipeVibe.BusinessLogic.MigrationsVideo
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class InitVideo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitVideo));
        
        string IMigrationMetadata.Id
        {
            get { return "202506071329238_InitVideo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
